title: Mr. White | The Professor's Lab Notes
theme: minima
markdown: kramdown

future: true

permalink: /:year/:month/:day/:title/

excerpt_separator: "<!--more-->"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author: R. Chandra Shekar
description: Penetration testing writeups and offensive security research
url: https://xo46.github.io

header_pages:
  - about.md
  - certifications.md
  - contact.md
